- name: Supervisor Check
  hosts: ~tag_Name_tech-sandbox-dev
  gather_facts: false
  sudo: yes
  tasks:
    - name: supervisor
      sensu_check: name=check2
                   standalone=true
                   interval=60
                   refresh=11440
                   occurrences=5
                   path='{{ check_path }}/checknumber2.json'
                   handlers=mon-ops
