- name: Add DMS Sensu Check
  hosts: ~tag_Name_tech-ops-sensu0-dev
  gather_facts: false
  become: yes
  vars:
    dms_tasks:
      - smu-mds-lms-to-ods2
  tasks:
    - pip:
        name: boto3
        version: 1.4.4
        virtualenv: '{{ plugin_path }}/venv'
    - sensu_check:
        name: 'dms_task_status_{{ item }}'
        command: '{{ plugin_path }}/venv/bin/python {{ plugin_path }}/dms_task_check.py --task-name {{ item }}'
        standalone: false
        interval: 60
        path: '{{ check_path }}/dw_toolbox_dms_task_status.json'
        occurrences: 3
        handlers: 'slack-data-systems-alerts,slack-monitoring,mon-ops'
        source: 'dwbi-prod-lms-dms-ods2-tasks'
        subscribers: 'roundrobin:blackbox'
      with_items: '{{ dms_tasks }}'
