- name: Add Sensu Check
  hosts: ~tag_Name_2u-test-bast-test.2u.com
  gather_facts: false
  become: yes
  tasks:
    sensu_check: name=custom_check_2
                 command='{{ plugin_path }}/check-procs.rb -f /var/run/nginx.pid'
                 standalone=true
                 interval=60
                 path='{{ check_path }}/check2.json'
                 occurrences=4
